plugins:
  - jekyll-relative-links
  - jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
titles_from_headings:
  enabled: false
theme: jekyll-theme-cayman
title: Slides
description: Miscellaneous slides
